/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Core.Pembelian_Obat;
import Core.SessionLogin;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Asus
 */
public class DashboardStokies extends javax.swing.JFrame {

    /**
     * Creates new form DashboardAdmin
     */
    String session = SessionLogin.getUser();
    public DashboardStokies() {
        initComponents();
        panelHide();
        pnl_home.show();
        lbl_namalengkap.setText(session);
    }
    
    private void onClick(JPanel panel){
        panel.setBackground(new Color(205, 136, 205));
    }
    
    private void onLeaveClick(JPanel panel){
        panel.setBackground(Color.white);
    }
    
    private void panelHide(){
        pnl_home.hide();
        pnl_laporanpembelian.hide();
        pnl_pembelianobat.hide();
        pnl_ubahpassword.hide();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_home = new javax.swing.JPanel();
        Indicator1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_pembelianobat = new javax.swing.JPanel();
        Indicator3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_laporanpembelian = new javax.swing.JPanel();
        Indicator4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_ubahpassword = new javax.swing.JPanel();
        Indicator5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JPanel();
        Indicator7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbl_namalengkap = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        pnl_home = new javax.swing.JPanel();
        pnl_form6 = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        jPanel47 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel48 = new javax.swing.JPanel();
        jPanel58 = new javax.swing.JPanel();
        pnl_pembelianobat = new javax.swing.JPanel();
        pnl_form2 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        txt_nofakturpb = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_pembelian = new javax.swing.JTable();
        jPanel26 = new javax.swing.JPanel();
        btn_batalpb = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        btn_hapuspb = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        btn_perbaruipb = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        btn_selesaipb = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        txt_nobatchpb = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        jLabel48 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        txt_namaobatpb = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        txt_hargabeli = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        jLabel61 = new javax.swing.JLabel();
        jSeparator26 = new javax.swing.JSeparator();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        txt_quantitypb = new javax.swing.JTextField();
        jSeparator27 = new javax.swing.JSeparator();
        jPanel30 = new javax.swing.JPanel();
        btn_tambahpb = new javax.swing.JLabel();
        cmb_satuan = new javax.swing.JComboBox<>();
        cmb_kategori = new javax.swing.JComboBox<>();
        cmb_supplier = new javax.swing.JComboBox<>();
        date_JatuhTempo = new com.toedter.calendar.JDateChooser();
        date_transaksi = new com.toedter.calendar.JDateChooser();
        date_Expired = new com.toedter.calendar.JDateChooser();
        pnl_laporanpembelian = new javax.swing.JPanel();
        pnl_form1 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        pnl_ubahpassword = new javax.swing.JPanel();
        pnl_form4 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        txt_passwordlamaup = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        jSeparator22 = new javax.swing.JSeparator();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        txt_passwordbaruup = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        jPanel44 = new javax.swing.JPanel();
        btn_batalup = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        btn_ubahpasswordup = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        txt_konfirmasipasswordup = new javax.swing.JTextField();
        jSeparator30 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setModalExclusionType(null);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home.setBackground(new java.awt.Color(255, 255, 255));
        btn_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
        });

        Indicator1.setBackground(new java.awt.Color(204, 0, 204));
        Indicator1.setOpaque(false);

        javax.swing.GroupLayout Indicator1Layout = new javax.swing.GroupLayout(Indicator1);
        Indicator1.setLayout(Indicator1Layout);
        Indicator1Layout.setHorizontalGroup(
            Indicator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Indicator1Layout.setVerticalGroup(
            Indicator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(181, 77, 180));
        jLabel1.setText("Home");

        javax.swing.GroupLayout btn_homeLayout = new javax.swing.GroupLayout(btn_home);
        btn_home.setLayout(btn_homeLayout);
        btn_homeLayout.setHorizontalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_homeLayout.createSequentialGroup()
                .addComponent(Indicator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn_homeLayout.setVerticalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Indicator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 290, -1));

        btn_pembelianobat.setBackground(new java.awt.Color(255, 255, 255));
        btn_pembelianobat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pembelianobat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pembelianobatMouseClicked(evt);
            }
        });

        Indicator3.setBackground(new java.awt.Color(204, 0, 204));
        Indicator3.setOpaque(false);

        javax.swing.GroupLayout Indicator3Layout = new javax.swing.GroupLayout(Indicator3);
        Indicator3.setLayout(Indicator3Layout);
        Indicator3Layout.setHorizontalGroup(
            Indicator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Indicator3Layout.setVerticalGroup(
            Indicator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(96, 83, 150));
        jLabel3.setText("Pembelian Obat");

        javax.swing.GroupLayout btn_pembelianobatLayout = new javax.swing.GroupLayout(btn_pembelianobat);
        btn_pembelianobat.setLayout(btn_pembelianobatLayout);
        btn_pembelianobatLayout.setHorizontalGroup(
            btn_pembelianobatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_pembelianobatLayout.createSequentialGroup()
                .addComponent(Indicator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn_pembelianobatLayout.setVerticalGroup(
            btn_pembelianobatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_pembelianobatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Indicator3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btn_pembelianobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 290, -1));

        btn_laporanpembelian.setBackground(new java.awt.Color(255, 255, 255));
        btn_laporanpembelian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_laporanpembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_laporanpembelianMouseClicked(evt);
            }
        });

        Indicator4.setBackground(new java.awt.Color(204, 0, 204));
        Indicator4.setOpaque(false);

        javax.swing.GroupLayout Indicator4Layout = new javax.swing.GroupLayout(Indicator4);
        Indicator4.setLayout(Indicator4Layout);
        Indicator4Layout.setHorizontalGroup(
            Indicator4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Indicator4Layout.setVerticalGroup(
            Indicator4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(96, 83, 150));
        jLabel4.setText("Laporan Pembelian");

        javax.swing.GroupLayout btn_laporanpembelianLayout = new javax.swing.GroupLayout(btn_laporanpembelian);
        btn_laporanpembelian.setLayout(btn_laporanpembelianLayout);
        btn_laporanpembelianLayout.setHorizontalGroup(
            btn_laporanpembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_laporanpembelianLayout.createSequentialGroup()
                .addComponent(Indicator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel4)
                .addGap(0, 94, Short.MAX_VALUE))
        );
        btn_laporanpembelianLayout.setVerticalGroup(
            btn_laporanpembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_laporanpembelianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Indicator4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btn_laporanpembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, -1));

        btn_ubahpassword.setBackground(new java.awt.Color(255, 255, 255));
        btn_ubahpassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ubahpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ubahpasswordMouseClicked(evt);
            }
        });

        Indicator5.setBackground(new java.awt.Color(204, 0, 204));
        Indicator5.setOpaque(false);

        javax.swing.GroupLayout Indicator5Layout = new javax.swing.GroupLayout(Indicator5);
        Indicator5.setLayout(Indicator5Layout);
        Indicator5Layout.setHorizontalGroup(
            Indicator5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Indicator5Layout.setVerticalGroup(
            Indicator5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(96, 83, 150));
        jLabel5.setText("Ubah Password");

        javax.swing.GroupLayout btn_ubahpasswordLayout = new javax.swing.GroupLayout(btn_ubahpassword);
        btn_ubahpassword.setLayout(btn_ubahpasswordLayout);
        btn_ubahpasswordLayout.setHorizontalGroup(
            btn_ubahpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ubahpasswordLayout.createSequentialGroup()
                .addComponent(Indicator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn_ubahpasswordLayout.setVerticalGroup(
            btn_ubahpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ubahpasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Indicator5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btn_ubahpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 290, -1));

        btn_logout.setBackground(new java.awt.Color(255, 255, 255));
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });

        Indicator7.setBackground(new java.awt.Color(204, 0, 204));
        Indicator7.setOpaque(false);

        javax.swing.GroupLayout Indicator7Layout = new javax.swing.GroupLayout(Indicator7);
        Indicator7.setLayout(Indicator7Layout);
        Indicator7Layout.setHorizontalGroup(
            Indicator7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Indicator7Layout.setVerticalGroup(
            Indicator7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(96, 83, 150));
        jLabel7.setText("Logout");

        javax.swing.GroupLayout btn_logoutLayout = new javax.swing.GroupLayout(btn_logout);
        btn_logout.setLayout(btn_logoutLayout);
        btn_logoutLayout.setHorizontalGroup(
            btn_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_logoutLayout.createSequentialGroup()
                .addComponent(Indicator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn_logoutLayout.setVerticalGroup(
            btn_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_logoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Indicator7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 290, -1));

        jPanel6.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel5.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Male-User.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        lbl_namalengkap.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_namalengkap.setForeground(new java.awt.Color(96, 83, 150));
        lbl_namalengkap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_namalengkap.setText("Nama Lengkap");
        jPanel1.add(lbl_namalengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 220, 28));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 770));

        jPanel2.setBackground(new java.awt.Color(247, 247, 247));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(96, 83, 150));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 173, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 210, 50));

        jPanel7.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 670, -1, -1));

        jPanel8.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 730, -1, -1));

        pnl_home.setBackground(new java.awt.Color(247, 247, 247));
        pnl_home.setOpaque(false);
        pnl_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_form6.setBackground(new java.awt.Color(247, 247, 247));
        pnl_form6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel46.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel46Layout = new javax.swing.GroupLayout(jPanel46);
        jPanel46.setLayout(jPanel46Layout);
        jPanel46Layout.setHorizontalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel46Layout.setVerticalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pnl_form6.add(jPanel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 80));

        jPanel47.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout jPanel47Layout = new javax.swing.GroupLayout(jPanel47);
        jPanel47.setLayout(jPanel47Layout);
        jPanel47Layout.setHorizontalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel47Layout.setVerticalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnl_form6.add(jPanel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(96, 83, 150));
        jLabel16.setText("Welcome Stokies");
        pnl_form6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        jPanel48.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel48Layout = new javax.swing.GroupLayout(jPanel48);
        jPanel48.setLayout(jPanel48Layout);
        jPanel48Layout.setHorizontalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel48Layout.setVerticalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pnl_form6.add(jPanel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 530, 20, 80));

        jPanel58.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout jPanel58Layout = new javax.swing.GroupLayout(jPanel58);
        jPanel58.setLayout(jPanel58Layout);
        jPanel58Layout.setHorizontalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel58Layout.setVerticalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnl_form6.add(jPanel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 590, 100, 20));

        pnl_home.add(pnl_form6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 930, 610));

        jPanel2.add(pnl_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 780));

        pnl_pembelianobat.setBackground(new java.awt.Color(247, 247, 247));
        pnl_pembelianobat.setOpaque(false);
        pnl_pembelianobat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_form2.setBackground(new java.awt.Color(247, 247, 247));
        pnl_form2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pnl_form2.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 80));

        jPanel23.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnl_form2.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(96, 83, 150));
        jLabel12.setText("Pembelian Obat");
        pnl_form2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanel24.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pnl_form2.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 530, 20, 80));

        jPanel25.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnl_form2.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 590, 100, 20));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(96, 83, 150));
        jLabel42.setText("No Faktur");
        pnl_form2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        txt_nofakturpb.setBackground(new java.awt.Color(247, 247, 247));
        txt_nofakturpb.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_nofakturpb.setForeground(new java.awt.Color(96, 83, 150));
        txt_nofakturpb.setBorder(null);
        pnl_form2.add(txt_nofakturpb, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 190, -1));

        jLabel43.setForeground(new java.awt.Color(96, 83, 150));
        jLabel43.setText(":");
        pnl_form2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        jSeparator11.setForeground(new java.awt.Color(96, 83, 150));
        jSeparator11.setAlignmentX(1.0F);
        jSeparator11.setAlignmentY(1.0F);
        jSeparator11.setPreferredSize(new java.awt.Dimension(50, 15));
        pnl_form2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 190, -1));

        jLabel44.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(96, 83, 150));
        jLabel44.setText("Supplier");
        pnl_form2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel45.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(96, 83, 150));
        jLabel45.setText(":");
        pnl_form2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jSeparator15.setForeground(new java.awt.Color(96, 83, 150));
        jSeparator15.setAlignmentX(1.0F);
        jSeparator15.setAlignmentY(1.0F);
        jSeparator15.setPreferredSize(new java.awt.Dimension(50, 15));
        pnl_form2.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 820, -1));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(96, 83, 150));
        jLabel49.setText(":");
        pnl_form2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, -1));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(96, 83, 150));
        jLabel50.setText("Jatuh Tempo");
        pnl_form2.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(96, 83, 150));
        jLabel52.setText(":");
        pnl_form2.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, -1));

        jSeparator17.setForeground(new java.awt.Color(96, 83, 150));
        jSeparator17.setAlignmentX(1.0F);
        jSeparator17.setAlignmentY(1.0F);
        jSeparator17.setPreferredSize(new java.awt.Dimension(50, 15));
        pnl_form2.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 320, -1));

        jSeparator18.setForeground(new java.awt.Color(96, 83, 150));
        jSeparator18.setAlignmentX(1.0F);
        jSeparator18.setAlignmentY(1.0F);
        jSeparator18.setPreferredSize(new java.awt.Dimension(50, 15));
        pnl_form2.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 320, 20));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tbl_pembelian.setBackground(new java.awt.Color(247, 247, 247));
        tbl_pembelian.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tbl_pembelian.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tbl_pembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Batch", "Nama Obat", "Kategori", "Satuan", "Harga Beli", "Expired Date", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_pembelian.setGridColor(new java.awt.Color(247, 247, 247));
        tbl_pembelian.setRowHeight(20);
        tbl_pembelian.setSelectionBackground(new java.awt.Color(96, 83, 150));
        tbl_pembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pembelianMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_pembelian);
        if (tbl_pembelian.getColumnModel().getColumnCount() > 0) {
            tbl_pembelian.getColumnModel().getColumn(0).setResizable(false);
            tbl_pembelian.getColumnModel().getColumn(1).setResizable(false);
            tbl_pembelian.getColumnModel().getColumn(2).setResizable(false);
            tbl_pembelian.getColumnModel().getColumn(3).setResizable(false);
            tbl_pembelian.getColumnModel().getColumn(4).setResizable(false);
            tbl_pembelian.getColumnModel().getColumn(5).setResizable(false);
            tbl_pembelian.getColumnModel().getColumn(6).setResizable(false);
        }

        pnl_form2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 690, 160));

        jPanel26.setBackground(new java.awt.Color(96, 83, 150));

        btn_batalpb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_batalpb.setForeground(new java.awt.Color(255, 255, 255));
        btn_batalpb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_batalpb.setText("Batal");
        btn_batalpb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_batalpb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_batalpbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addComponent(btn_batalpb, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_batalpb, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnl_form2.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, -1, 30));

        jPanel27.setBackground(new java.awt.Color(96, 83, 150));

        btn_hapuspb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_hapuspb.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapuspb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_hapuspb.setText("Hapus");
        btn_hapuspb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_hapuspb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapuspbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                .addComponent(btn_hapuspb, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_hapuspb, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnl_form2.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, -1, 30));

        jPanel28.setBackground(new java.awt.Color(96, 83, 150));

        btn_perbaruipb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_perbaruipb.setForeground(new java.awt.Color(255, 255, 255));
        btn_perbaruipb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_perbaruipb.setText("Perbarui");
        btn_perbaruipb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_perbaruipb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_perbaruipbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addComponent(btn_perbaruipb, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_perbaruipb, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnl_form2.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, -1, 30));

        jPanel29.setBackground(new java.awt.Color(96, 83, 150));

        btn_selesaipb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_selesaipb.setForeground(new java.awt.Color(255, 255, 255));
        btn_selesaipb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_selesaipb.setText("Selesai");
        btn_selesaipb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_selesaipb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_selesaipbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel29Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_selesaipb, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_selesaipb, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnl_form2.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, -1, 30));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(96, 83, 150));
        jLabel51.setText("Tanggal Transaksi");
        pnl_form2.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, 20));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(96, 83, 150));
        jLabel46.setText("No Batch");
        pnl_form2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel47.setForeground(new java.awt.Color(96, 83, 150));
        jLabel47.setText(":");
        pnl_form2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        txt_nobatchpb.setBackground(new java.awt.Color(247, 247, 247));
        txt_nobatchpb.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_nobatchpb.setForeground(new java.awt.Color(96, 83, 150));
        txt_nobatchpb.setBorder(null);
        pnl_form2.add(txt_nobatchpb, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 190, -1));

        jSeparator19.setForeground(new java.awt.Color(96, 83, 150));
        jSeparator19.setAlignmentX(1.0F);
        jSeparator19.setAlignmentY(1.0F);
        jSeparator19.setPreferredSize(new java.awt.Dimension(50, 15));
        pnl_form2.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 190, -1));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(96, 83, 150));
        jLabel48.setText("Nama Obat");
        pnl_form2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel53.setForeground(new java.awt.Color(96, 83, 150));
        jLabel53.setText(":");
        pnl_form2.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        txt_namaobatpb.setBackground(new java.awt.Color(247, 247, 247));
        txt_namaobatpb.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_namaobatpb.setForeground(new java.awt.Color(96, 83, 150));
        txt_namaobatpb.setBorder(null);
        txt_namaobatpb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaobatpbActionPerformed(evt);
            }
        });
        pnl_form2.add(txt_namaobatpb, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 190, -1));

        jSeparator20.setForeground(new java.awt.Color(96, 83, 150));
        jSeparator20.setAlignmentX(1.0F);
        jSeparator20.setAlignmentY(1.0F);
        jSeparator20.setPreferredSize(new java.awt.Dimension(50, 15));
        pnl_form2.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 190, -1));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(96, 83, 150));
        jLabel54.setText("Kategori");
        pnl_form2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        jLabel55.setForeground(new java.awt.Color(96, 83, 150));
        jLabel55.setText(":");
        pnl_form2.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(96, 83, 150));
        jLabel56.setText("Satuan");
        pnl_form2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        jLabel57.setForeground(new java.awt.Color(96, 83, 150));
        jLabel57.setText(":");
        pnl_form2.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));

        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(96, 83, 150));
        jLabel59.setText("Harga Beli");
        pnl_form2.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jLabel60.setForeground(new java.awt.Color(96, 83, 150));
        jLabel60.setText(":");
        pnl_form2.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        txt_hargabeli.setBackground(new java.awt.Color(247, 247, 247));
        txt_hargabeli.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_hargabeli.setForeground(new java.awt.Color(96, 83, 150));
        txt_hargabeli.setBorder(null);
        pnl_form2.add(txt_hargabeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 190, -1));

        jSeparator25.setForeground(new java.awt.Color(96, 83, 150));
        jSeparator25.setAlignmentX(1.0F);
        jSeparator25.setAlignmentY(1.0F);
        jSeparator25.setPreferredSize(new java.awt.Dimension(50, 15));
        pnl_form2.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 190, -1));

        jLabel61.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(96, 83, 150));
        jLabel61.setText("Expired Date");
        pnl_form2.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        jSeparator26.setForeground(new java.awt.Color(96, 83, 150));
        jSeparator26.setAlignmentX(1.0F);
        jSeparator26.setAlignmentY(1.0F);
        jSeparator26.setPreferredSize(new java.awt.Dimension(50, 15));
        pnl_form2.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 190, -1));

        jLabel62.setForeground(new java.awt.Color(96, 83, 150));
        jLabel62.setText(":");
        pnl_form2.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, -1));

        jLabel63.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(96, 83, 150));
        jLabel63.setText("Quantity");
        pnl_form2.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, -1, -1));

        jLabel64.setForeground(new java.awt.Color(96, 83, 150));
        jLabel64.setText(":");
        pnl_form2.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, -1, -1));

        txt_quantitypb.setBackground(new java.awt.Color(247, 247, 247));
        txt_quantitypb.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_quantitypb.setForeground(new java.awt.Color(96, 83, 150));
        txt_quantitypb.setBorder(null);
        pnl_form2.add(txt_quantitypb, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 220, 80, -1));

        jSeparator27.setForeground(new java.awt.Color(96, 83, 150));
        jSeparator27.setAlignmentX(1.0F);
        jSeparator27.setAlignmentY(1.0F);
        jSeparator27.setPreferredSize(new java.awt.Dimension(50, 15));
        pnl_form2.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 80, -1));

        jPanel30.setBackground(new java.awt.Color(96, 83, 150));

        btn_tambahpb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_tambahpb.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambahpb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_tambahpb.setText("Tambah");
        btn_tambahpb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tambahpb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahpbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_tambahpb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_tambahpb, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnl_form2.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, -1, 30));

        pnl_form2.add(cmb_satuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 190, -1));

        pnl_form2.add(cmb_kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 190, -1));

        cmb_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_supplierActionPerformed(evt);
            }
        });
        pnl_form2.add(cmb_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 190, -1));

        date_JatuhTempo.setDateFormatString("dd - MMM - yyyy");
        pnl_form2.add(date_JatuhTempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 320, -1));

        date_transaksi.setDateFormatString("dd - MMM - yyyy");
        pnl_form2.add(date_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 320, -1));

        date_Expired.setDateFormatString("dd - MMM - yyyy");
        pnl_form2.add(date_Expired, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 190, -1));

        pnl_pembelianobat.add(pnl_form2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 930, 610));

        jPanel2.add(pnl_pembelianobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 780));

        pnl_laporanpembelian.setBackground(new java.awt.Color(247, 247, 247));
        pnl_laporanpembelian.setOpaque(false);
        pnl_laporanpembelian.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_form1.setBackground(new java.awt.Color(247, 247, 247));
        pnl_form1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pnl_form1.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 80));

        jPanel19.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnl_form1.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(96, 83, 150));
        jLabel11.setText("Laporan Pembelian");
        pnl_form1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanel20.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pnl_form1.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 530, 20, 80));

        jPanel21.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnl_form1.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 590, 100, 20));

        pnl_laporanpembelian.add(pnl_form1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 930, 610));

        jPanel2.add(pnl_laporanpembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 780));

        pnl_ubahpassword.setBackground(new java.awt.Color(247, 247, 247));
        pnl_ubahpassword.setOpaque(false);
        pnl_ubahpassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_form4.setBackground(new java.awt.Color(247, 247, 247));
        pnl_form4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel40.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pnl_form4.add(jPanel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 80));

        jPanel41.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnl_form4.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(96, 83, 150));
        jLabel14.setText("Ubah Password");
        pnl_form4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanel42.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pnl_form4.add(jPanel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 530, 20, 80));

        jPanel43.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnl_form4.add(jPanel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 590, 100, 20));

        jLabel68.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(96, 83, 150));
        jLabel68.setText("Password Lama");
        pnl_form4.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        txt_passwordlamaup.setBackground(new java.awt.Color(247, 247, 247));
        txt_passwordlamaup.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_passwordlamaup.setForeground(new java.awt.Color(96, 83, 150));
        txt_passwordlamaup.setBorder(null);
        pnl_form4.add(txt_passwordlamaup, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 620, -1));

        jLabel69.setForeground(new java.awt.Color(96, 83, 150));
        jLabel69.setText(":");
        pnl_form4.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 10, -1));

        jSeparator22.setForeground(new java.awt.Color(96, 83, 150));
        jSeparator22.setAlignmentX(1.0F);
        jSeparator22.setAlignmentY(1.0F);
        jSeparator22.setPreferredSize(new java.awt.Dimension(50, 15));
        pnl_form4.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 620, -1));

        jLabel70.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 14)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(96, 83, 150));
        jLabel70.setText("Password Baru");
        pnl_form4.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel71.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 14)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(96, 83, 150));
        jLabel71.setText(":");
        pnl_form4.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 10, -1));

        txt_passwordbaruup.setBackground(new java.awt.Color(247, 247, 247));
        txt_passwordbaruup.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 13)); // NOI18N
        txt_passwordbaruup.setForeground(new java.awt.Color(96, 83, 150));
        txt_passwordbaruup.setBorder(null);
        pnl_form4.add(txt_passwordbaruup, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 620, 19));

        jSeparator23.setForeground(new java.awt.Color(96, 83, 150));
        jSeparator23.setAlignmentX(1.0F);
        jSeparator23.setAlignmentY(1.0F);
        jSeparator23.setPreferredSize(new java.awt.Dimension(50, 15));
        pnl_form4.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 620, -1));

        jPanel44.setBackground(new java.awt.Color(96, 83, 150));

        btn_batalup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_batalup.setForeground(new java.awt.Color(255, 255, 255));
        btn_batalup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_batalup.setText("Batal");

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addComponent(btn_batalup, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addComponent(btn_batalup, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnl_form4.add(jPanel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, -1, 30));

        jPanel45.setBackground(new java.awt.Color(96, 83, 150));

        btn_ubahpasswordup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ubahpasswordup.setForeground(new java.awt.Color(255, 255, 255));
        btn_ubahpasswordup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_ubahpasswordup.setText("Ubah");

        javax.swing.GroupLayout jPanel45Layout = new javax.swing.GroupLayout(jPanel45);
        jPanel45.setLayout(jPanel45Layout);
        jPanel45Layout.setHorizontalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel45Layout.createSequentialGroup()
                .addComponent(btn_ubahpasswordup, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel45Layout.setVerticalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel45Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_ubahpasswordup, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_form4.add(jPanel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, -1, 30));

        jLabel94.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 14)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(96, 83, 150));
        jLabel94.setText("Konfirmasi Password");
        pnl_form4.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel95.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 14)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(96, 83, 150));
        jLabel95.setText(":");
        pnl_form4.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 10, -1));

        txt_konfirmasipasswordup.setBackground(new java.awt.Color(247, 247, 247));
        txt_konfirmasipasswordup.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 13)); // NOI18N
        txt_konfirmasipasswordup.setForeground(new java.awt.Color(96, 83, 150));
        txt_konfirmasipasswordup.setBorder(null);
        pnl_form4.add(txt_konfirmasipasswordup, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 620, 19));

        jSeparator30.setForeground(new java.awt.Color(96, 83, 150));
        jSeparator30.setAlignmentX(1.0F);
        jSeparator30.setAlignmentY(1.0F);
        jSeparator30.setPreferredSize(new java.awt.Dimension(50, 15));
        pnl_form4.add(jSeparator30, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 620, -1));

        pnl_ubahpassword.add(pnl_form4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 930, 610));

        jPanel2.add(pnl_ubahpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 780));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1070, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
        onClick(btn_home);
        onLeaveClick(btn_pembelianobat);
        onLeaveClick(btn_laporanpembelian);
        onLeaveClick(btn_ubahpassword);
        onLeaveClick(btn_logout);
        
        Indicator1.setOpaque(true);
        Indicator3.setOpaque(false);
        Indicator4.setOpaque(false);
        Indicator5.setOpaque(false);
        Indicator7.setOpaque(false);
        
        panelHide();
        pnl_home.show();
    }//GEN-LAST:event_btn_homeMouseClicked

    private void btn_pembelianobatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembelianobatMouseClicked
        onClick(btn_pembelianobat);
        onLeaveClick(btn_home);
        onLeaveClick(btn_laporanpembelian);
        onLeaveClick(btn_ubahpassword);
        onLeaveClick(btn_logout);
        
        Indicator3.setOpaque(true);
        Indicator1.setOpaque(false);
        Indicator4.setOpaque(false);
        Indicator5.setOpaque(false);
        Indicator7.setOpaque(false);
        
        panelHide();
        pnl_pembelianobat.show();
        try {
            Pembelian_Obat.comboBox(cmb_satuan);
            Pembelian_Obat.comboBoxKategori(cmb_kategori);
            Pembelian_Obat.comboBoxSupplier(cmb_supplier);
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_btn_pembelianobatMouseClicked

    private void btn_laporanpembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanpembelianMouseClicked
        onClick(btn_laporanpembelian);
        onLeaveClick(btn_pembelianobat);
        onLeaveClick(btn_home);
        onLeaveClick(btn_ubahpassword);
        onLeaveClick(btn_logout);
        
        Indicator4.setOpaque(true);
        Indicator3.setOpaque(false);
        Indicator1.setOpaque(false);
        Indicator5.setOpaque(false);
        Indicator7.setOpaque(false);
        
        panelHide();
        pnl_laporanpembelian.show();
    }//GEN-LAST:event_btn_laporanpembelianMouseClicked

    private void btn_ubahpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ubahpasswordMouseClicked
        onClick(btn_ubahpassword);
        onLeaveClick(btn_pembelianobat);
        onLeaveClick(btn_laporanpembelian);
        onLeaveClick(btn_home);
        onLeaveClick(btn_logout);
        
        Indicator5.setOpaque(true);
        Indicator3.setOpaque(false);
        Indicator4.setOpaque(false);
        Indicator1.setOpaque(false);
        Indicator7.setOpaque(false);
        
        panelHide();
        pnl_ubahpassword.show();
    }//GEN-LAST:event_btn_ubahpasswordMouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        onClick(btn_logout);
        onLeaveClick(btn_pembelianobat);
        onLeaveClick(btn_laporanpembelian);
        onLeaveClick(btn_ubahpassword);
        onLeaveClick(btn_home);
        
        Indicator7.setOpaque(true);
        Indicator3.setOpaque(false);
        Indicator4.setOpaque(false);
        Indicator5.setOpaque(false);
        Indicator1.setOpaque(false);
        
        this.dispose();
        FrmLogin fl = new FrmLogin();
        fl.show();
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);;
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txt_namaobatpbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaobatpbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaobatpbActionPerformed

    private void ClearForm(){
        if(tbl_pembelian.getRowCount() == 0){
            txt_nofakturpb.setText("");
            txt_nofakturpb.enable(true);
            cmb_supplier.setSelectedIndex(0);
            cmb_supplier.enable(true);
            txt_nobatchpb.setText("");
            txt_namaobatpb.setText("");
            cmb_kategori.setSelectedIndex(0);
            cmb_satuan.setSelectedIndex(0);
            txt_hargabeli.setText("");
            txt_quantitypb.setText("");
            Pembelian_Obat.selectedRowIndex = -1;
            
        }
        else{
            txt_nofakturpb.disable();
            cmb_supplier.disable();
            txt_nobatchpb.setText("");
            txt_namaobatpb.setText("");
            cmb_kategori.setSelectedIndex(0);
            cmb_satuan.setSelectedIndex(0);
            txt_hargabeli.setText("");
            txt_quantitypb.setText("");
            Pembelian_Obat.selectedRowIndex = -1;
        }
    }
    
    private void btn_tambahpbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahpbMouseClicked
        if(txt_nobatchpb.getText().equals("")|| txt_namaobatpb.getText().equals("")|| txt_hargabeli.getText().equals("") || date_Expired.getDateFormatString().equals("") || txt_quantitypb.equals("")){
            JOptionPane.showMessageDialog(null, "Masih Ada Form Yang Kosong");
        }
        else{
            Pembelian_Obat.insertToJtablePembelian(tbl_pembelian, txt_nobatchpb, txt_namaobatpb, cmb_kategori, cmb_satuan, txt_hargabeli, date_Expired, txt_quantitypb);   
            ClearForm();
        }
    }//GEN-LAST:event_btn_tambahpbMouseClicked

    private void tbl_pembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pembelianMouseClicked
        Pembelian_Obat.getDataTable(tbl_pembelian, txt_nobatchpb, txt_namaobatpb, cmb_kategori, cmb_satuan, txt_hargabeli, date_Expired, txt_quantitypb);
    }//GEN-LAST:event_tbl_pembelianMouseClicked

    private void btn_hapuspbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapuspbMouseClicked
        if(tbl_pembelian.getRowCount() == 0 || Pembelian_Obat.selectedRowIndex == -1){
            JOptionPane.showMessageDialog(null, "Maaf Anda Belum Memilih");
        }else{
            Pembelian_Obat.removeRowTable(tbl_pembelian);
            ClearForm();
        }
    }//GEN-LAST:event_btn_hapuspbMouseClicked

    private void btn_perbaruipbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_perbaruipbMouseClicked
        if(tbl_pembelian.getRowCount() == 0 || Pembelian_Obat.selectedRowIndex == -1){
            JOptionPane.showMessageDialog(null, "Maaf Anda Belum Memilih");
        }else{
        Pembelian_Obat.updateRowTable(tbl_pembelian, txt_nobatchpb, txt_namaobatpb, cmb_kategori, cmb_satuan, txt_hargabeli, date_Expired, txt_quantitypb);
        ClearForm();
        }
    }//GEN-LAST:event_btn_perbaruipbMouseClicked

    private void btn_batalpbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalpbMouseClicked
        ClearForm();
    }//GEN-LAST:event_btn_batalpbMouseClicked

    private void btn_selesaipbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_selesaipbMouseClicked
        try {
            Pembelian_Obat.insert_pembelian(txt_nofakturpb, date_transaksi, date_JatuhTempo, cmb_supplier);
            try {
                Pembelian_Obat.insertObat(tbl_pembelian);
            } catch (Exception ex) {
                Logger.getLogger(DashboardStokies.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Data Berhasil Dimasukkan");
        } catch (SQLException ex) {
            Logger.getLogger(DashboardStokies.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_selesaipbMouseClicked

    private void cmb_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_supplierActionPerformed

    }//GEN-LAST:event_cmb_supplierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardStokies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardStokies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardStokies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardStokies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardStokies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Indicator1;
    private javax.swing.JPanel Indicator3;
    private javax.swing.JPanel Indicator4;
    private javax.swing.JPanel Indicator5;
    private javax.swing.JPanel Indicator7;
    private javax.swing.JLabel btn_batalpb;
    private javax.swing.JLabel btn_batalup;
    private javax.swing.JLabel btn_hapuspb;
    private javax.swing.JPanel btn_home;
    private javax.swing.JPanel btn_laporanpembelian;
    private javax.swing.JPanel btn_logout;
    private javax.swing.JPanel btn_pembelianobat;
    private javax.swing.JLabel btn_perbaruipb;
    private javax.swing.JLabel btn_selesaipb;
    private javax.swing.JLabel btn_tambahpb;
    private javax.swing.JPanel btn_ubahpassword;
    private javax.swing.JLabel btn_ubahpasswordup;
    private javax.swing.JComboBox<String> cmb_kategori;
    private javax.swing.JComboBox<String> cmb_satuan;
    private javax.swing.JComboBox<String> cmb_supplier;
    private com.toedter.calendar.JDateChooser date_Expired;
    private com.toedter.calendar.JDateChooser date_JatuhTempo;
    private com.toedter.calendar.JDateChooser date_transaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JLabel lbl_namalengkap;
    private javax.swing.JPanel pnl_form1;
    private javax.swing.JPanel pnl_form2;
    private javax.swing.JPanel pnl_form4;
    private javax.swing.JPanel pnl_form6;
    private javax.swing.JPanel pnl_home;
    private javax.swing.JPanel pnl_laporanpembelian;
    private javax.swing.JPanel pnl_pembelianobat;
    private javax.swing.JPanel pnl_ubahpassword;
    private javax.swing.JTable tbl_pembelian;
    private javax.swing.JTextField txt_hargabeli;
    private javax.swing.JTextField txt_konfirmasipasswordup;
    private javax.swing.JTextField txt_namaobatpb;
    private javax.swing.JTextField txt_nobatchpb;
    private javax.swing.JTextField txt_nofakturpb;
    private javax.swing.JTextField txt_passwordbaruup;
    private javax.swing.JTextField txt_passwordlamaup;
    private javax.swing.JTextField txt_quantitypb;
    // End of variables declaration//GEN-END:variables
}
