/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.awt.Color;
import javax.swing.JPanel;
import Core.Kategori;
import Core.Satuan;
import Core.SessionLogin;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class DashboardGudang extends javax.swing.JFrame {

    /**
     * Creates new form DashboardAdmin
     */
    String login = SessionLogin.getUser();
    int id_kategori,id_satuan;
    public DashboardGudang() {
        initComponents();
        panelHide();
        pnl_home.show();
        lbl_namalengkap.setText(login);
    }
    
    private void onClick(JPanel panel){
        panel.setBackground(new Color(205, 136, 205));
    }
    
    private void onLeaveClick(JPanel panel){
        panel.setBackground(Color.white);
    }
    
    private void panelHide(){
        pnl_home.hide();
        pnl_satuanobat.hide();
        pnl_dataobat.hide();
        pnl_kategoriobat.hide();
        pnl_ubahpassword.hide();
    }
    private void clearKategori(){
        txt_kategoriobat.setText("");
    }
    private void clearSatuan(){
        txt_satuanobat.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_home = new javax.swing.JPanel();
        Indicator1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_kategoriobat = new javax.swing.JPanel();
        Indicator3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_satuanobat = new javax.swing.JPanel();
        Indicator4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_dataobat = new javax.swing.JPanel();
        Indicator6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JPanel();
        Indicator7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbl_namalengkap = new javax.swing.JLabel();
        btn_ubahpassword = new javax.swing.JPanel();
        Indicator8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        pnl_home = new javax.swing.JPanel();
        pnl_form6 = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        jPanel47 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel48 = new javax.swing.JPanel();
        jPanel58 = new javax.swing.JPanel();
        pnl_kategoriobat = new javax.swing.JPanel();
        pnl_form2 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        txt_kategoriobat = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_kategoriobat = new javax.swing.JTable();
        jPanel26 = new javax.swing.JPanel();
        btn_batalko = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        btn_hapusko = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        btn_perbaruiko = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        btn_tambahko = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        pnl_satuanobat = new javax.swing.JPanel();
        pnl_form3 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        txt_satuanobat = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_satuanobat = new javax.swing.JTable();
        jPanel35 = new javax.swing.JPanel();
        btn_batalso = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        btn_hapusso = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        btn_perbaruiso = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        btn_tambahso = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        pnl_dataobat = new javax.swing.JPanel();
        pnl_form5 = new javax.swing.JPanel();
        jPanel49 = new javax.swing.JPanel();
        jPanel50 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel51 = new javax.swing.JPanel();
        jPanel52 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        txt_satuanobat1 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_satuanobat1 = new javax.swing.JTable();
        jLabel48 = new javax.swing.JLabel();
        pnl_ubahpassword = new javax.swing.JPanel();
        pnl_form4 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        txt_passwordlamaup = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        jSeparator22 = new javax.swing.JSeparator();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        txt_passwordbaruup = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        jPanel44 = new javax.swing.JPanel();
        btn_batalup = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        btn_ubahpasswordup = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        txt_konfirmasipasswordup = new javax.swing.JTextField();
        jSeparator30 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setModalExclusionType(null);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home.setBackground(new java.awt.Color(255, 255, 255));
        btn_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
        });

        Indicator1.setBackground(new java.awt.Color(204, 0, 204));
        Indicator1.setOpaque(false);

        javax.swing.GroupLayout Indicator1Layout = new javax.swing.GroupLayout(Indicator1);
        Indicator1.setLayout(Indicator1Layout);
        Indicator1Layout.setHorizontalGroup(
            Indicator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Indicator1Layout.setVerticalGroup(
            Indicator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(181, 77, 180));
        jLabel1.setText("Home");

        javax.swing.GroupLayout btn_homeLayout = new javax.swing.GroupLayout(btn_home);
        btn_home.setLayout(btn_homeLayout);
        btn_homeLayout.setHorizontalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_homeLayout.createSequentialGroup()
                .addComponent(Indicator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn_homeLayout.setVerticalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Indicator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 290, -1));

        btn_kategoriobat.setBackground(new java.awt.Color(255, 255, 255));
        btn_kategoriobat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_kategoriobat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kategoriobatMouseClicked(evt);
            }
        });

        Indicator3.setBackground(new java.awt.Color(204, 0, 204));
        Indicator3.setOpaque(false);

        javax.swing.GroupLayout Indicator3Layout = new javax.swing.GroupLayout(Indicator3);
        Indicator3.setLayout(Indicator3Layout);
        Indicator3Layout.setHorizontalGroup(
            Indicator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Indicator3Layout.setVerticalGroup(
            Indicator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(96, 83, 150));
        jLabel3.setText("Kategori Obat");

        javax.swing.GroupLayout btn_kategoriobatLayout = new javax.swing.GroupLayout(btn_kategoriobat);
        btn_kategoriobat.setLayout(btn_kategoriobatLayout);
        btn_kategoriobatLayout.setHorizontalGroup(
            btn_kategoriobatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_kategoriobatLayout.createSequentialGroup()
                .addComponent(Indicator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn_kategoriobatLayout.setVerticalGroup(
            btn_kategoriobatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_kategoriobatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Indicator3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btn_kategoriobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 290, -1));

        btn_satuanobat.setBackground(new java.awt.Color(255, 255, 255));
        btn_satuanobat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_satuanobat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_satuanobatMouseClicked(evt);
            }
        });

        Indicator4.setBackground(new java.awt.Color(204, 0, 204));
        Indicator4.setOpaque(false);

        javax.swing.GroupLayout Indicator4Layout = new javax.swing.GroupLayout(Indicator4);
        Indicator4.setLayout(Indicator4Layout);
        Indicator4Layout.setHorizontalGroup(
            Indicator4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Indicator4Layout.setVerticalGroup(
            Indicator4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(96, 83, 150));
        jLabel4.setText("Satuan Obat");

        javax.swing.GroupLayout btn_satuanobatLayout = new javax.swing.GroupLayout(btn_satuanobat);
        btn_satuanobat.setLayout(btn_satuanobatLayout);
        btn_satuanobatLayout.setHorizontalGroup(
            btn_satuanobatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_satuanobatLayout.createSequentialGroup()
                .addComponent(Indicator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel4)
                .addGap(0, 142, Short.MAX_VALUE))
        );
        btn_satuanobatLayout.setVerticalGroup(
            btn_satuanobatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_satuanobatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Indicator4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btn_satuanobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 290, -1));

        btn_dataobat.setBackground(new java.awt.Color(255, 255, 255));
        btn_dataobat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_dataobat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dataobatMouseClicked(evt);
            }
        });

        Indicator6.setBackground(new java.awt.Color(204, 0, 204));
        Indicator6.setOpaque(false);

        javax.swing.GroupLayout Indicator6Layout = new javax.swing.GroupLayout(Indicator6);
        Indicator6.setLayout(Indicator6Layout);
        Indicator6Layout.setHorizontalGroup(
            Indicator6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Indicator6Layout.setVerticalGroup(
            Indicator6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(96, 83, 150));
        jLabel6.setText("Data Obat");

        javax.swing.GroupLayout btn_dataobatLayout = new javax.swing.GroupLayout(btn_dataobat);
        btn_dataobat.setLayout(btn_dataobatLayout);
        btn_dataobatLayout.setHorizontalGroup(
            btn_dataobatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_dataobatLayout.createSequentialGroup()
                .addComponent(Indicator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn_dataobatLayout.setVerticalGroup(
            btn_dataobatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_dataobatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Indicator6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btn_dataobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 290, -1));

        btn_logout.setBackground(new java.awt.Color(255, 255, 255));
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });

        Indicator7.setBackground(new java.awt.Color(204, 0, 204));
        Indicator7.setOpaque(false);

        javax.swing.GroupLayout Indicator7Layout = new javax.swing.GroupLayout(Indicator7);
        Indicator7.setLayout(Indicator7Layout);
        Indicator7Layout.setHorizontalGroup(
            Indicator7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Indicator7Layout.setVerticalGroup(
            Indicator7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(96, 83, 150));
        jLabel7.setText("Logout");

        javax.swing.GroupLayout btn_logoutLayout = new javax.swing.GroupLayout(btn_logout);
        btn_logout.setLayout(btn_logoutLayout);
        btn_logoutLayout.setHorizontalGroup(
            btn_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_logoutLayout.createSequentialGroup()
                .addComponent(Indicator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel7)
                .addGap(0, 174, Short.MAX_VALUE))
        );
        btn_logoutLayout.setVerticalGroup(
            btn_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_logoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Indicator7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 290, 50));

        jPanel6.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel5.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Male-User.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 110, 90));

        lbl_namalengkap.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_namalengkap.setForeground(new java.awt.Color(96, 83, 150));
        lbl_namalengkap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_namalengkap.setText("nama lengkap");
        jPanel1.add(lbl_namalengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 220, 28));

        btn_ubahpassword.setBackground(new java.awt.Color(255, 255, 255));
        btn_ubahpassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ubahpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ubahpasswordMouseClicked(evt);
            }
        });

        Indicator8.setBackground(new java.awt.Color(204, 0, 204));
        Indicator8.setOpaque(false);

        javax.swing.GroupLayout Indicator8Layout = new javax.swing.GroupLayout(Indicator8);
        Indicator8.setLayout(Indicator8Layout);
        Indicator8Layout.setHorizontalGroup(
            Indicator8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Indicator8Layout.setVerticalGroup(
            Indicator8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(96, 83, 150));
        jLabel8.setText("Ubah Password");

        javax.swing.GroupLayout btn_ubahpasswordLayout = new javax.swing.GroupLayout(btn_ubahpassword);
        btn_ubahpassword.setLayout(btn_ubahpasswordLayout);
        btn_ubahpasswordLayout.setHorizontalGroup(
            btn_ubahpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ubahpasswordLayout.createSequentialGroup()
                .addComponent(Indicator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel8)
                .addGap(0, 121, Short.MAX_VALUE))
        );
        btn_ubahpasswordLayout.setVerticalGroup(
            btn_ubahpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ubahpasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Indicator8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btn_ubahpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 290, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 770));

        jPanel2.setBackground(new java.awt.Color(247, 247, 247));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(96, 83, 150));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 173, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 210, 50));

        jPanel7.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 670, -1, -1));

        jPanel8.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 730, -1, -1));

        pnl_home.setBackground(new java.awt.Color(247, 247, 247));
        pnl_home.setOpaque(false);
        pnl_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_form6.setBackground(new java.awt.Color(247, 247, 247));
        pnl_form6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel46.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel46Layout = new javax.swing.GroupLayout(jPanel46);
        jPanel46.setLayout(jPanel46Layout);
        jPanel46Layout.setHorizontalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel46Layout.setVerticalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pnl_form6.add(jPanel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 80));

        jPanel47.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout jPanel47Layout = new javax.swing.GroupLayout(jPanel47);
        jPanel47.setLayout(jPanel47Layout);
        jPanel47Layout.setHorizontalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel47Layout.setVerticalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnl_form6.add(jPanel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(96, 83, 150));
        jLabel16.setText("Welcome Gudang");
        pnl_form6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        jPanel48.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel48Layout = new javax.swing.GroupLayout(jPanel48);
        jPanel48.setLayout(jPanel48Layout);
        jPanel48Layout.setHorizontalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel48Layout.setVerticalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pnl_form6.add(jPanel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 530, 20, 80));

        jPanel58.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout jPanel58Layout = new javax.swing.GroupLayout(jPanel58);
        jPanel58.setLayout(jPanel58Layout);
        jPanel58Layout.setHorizontalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel58Layout.setVerticalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnl_form6.add(jPanel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 590, 100, 20));

        pnl_home.add(pnl_form6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 930, 610));

        jPanel2.add(pnl_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 780));

        pnl_kategoriobat.setBackground(new java.awt.Color(247, 247, 247));
        pnl_kategoriobat.setOpaque(false);
        pnl_kategoriobat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_form2.setBackground(new java.awt.Color(247, 247, 247));
        pnl_form2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pnl_form2.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 80));

        jPanel23.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnl_form2.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(96, 83, 150));
        jLabel12.setText("Kategori Obat");
        pnl_form2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanel24.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pnl_form2.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 530, 20, 80));

        jPanel25.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnl_form2.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 590, 100, 20));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(96, 83, 150));
        jLabel42.setText("Kategori Obat");
        pnl_form2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        txt_kategoriobat.setBackground(new java.awt.Color(247, 247, 247));
        txt_kategoriobat.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_kategoriobat.setForeground(new java.awt.Color(96, 83, 150));
        txt_kategoriobat.setBorder(null);
        pnl_form2.add(txt_kategoriobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 690, -1));

        jLabel43.setForeground(new java.awt.Color(96, 83, 150));
        jLabel43.setText(":");
        pnl_form2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 10, -1));

        jSeparator11.setForeground(new java.awt.Color(96, 83, 150));
        jSeparator11.setAlignmentX(1.0F);
        jSeparator11.setAlignmentY(1.0F);
        jSeparator11.setPreferredSize(new java.awt.Dimension(50, 15));
        pnl_form2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 690, -1));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tbl_kategoriobat.setBackground(new java.awt.Color(247, 247, 247));
        tbl_kategoriobat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tbl_kategoriobat.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tbl_kategoriobat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Kategori"
            }
        ));
        tbl_kategoriobat.setGridColor(new java.awt.Color(247, 247, 247));
        tbl_kategoriobat.setRowHeight(20);
        tbl_kategoriobat.setSelectionBackground(new java.awt.Color(96, 83, 150));
        tbl_kategoriobat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_kategoriobatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_kategoriobat);

        pnl_form2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 820, 360));

        jPanel26.setBackground(new java.awt.Color(96, 83, 150));

        btn_batalko.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_batalko.setForeground(new java.awt.Color(255, 255, 255));
        btn_batalko.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_batalko.setText("Batal");
        btn_batalko.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_batalko.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_batalkoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addComponent(btn_batalko, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addComponent(btn_batalko, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnl_form2.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, -1, 30));

        jPanel27.setBackground(new java.awt.Color(96, 83, 150));

        btn_hapusko.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_hapusko.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapusko.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_hapusko.setText("Hapus");
        btn_hapusko.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_hapusko.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapuskoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addComponent(btn_hapusko, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_hapusko, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_form2.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, -1, 30));

        jPanel28.setBackground(new java.awt.Color(96, 83, 150));

        btn_perbaruiko.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_perbaruiko.setForeground(new java.awt.Color(255, 255, 255));
        btn_perbaruiko.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_perbaruiko.setText("Perbarui");
        btn_perbaruiko.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_perbaruiko.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_perbaruikoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addComponent(btn_perbaruiko, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addComponent(btn_perbaruiko, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnl_form2.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, -1, 30));

        jPanel29.setBackground(new java.awt.Color(96, 83, 150));

        btn_tambahko.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_tambahko.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambahko.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_tambahko.setText("Tambah");
        btn_tambahko.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tambahko.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahkoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_tambahko, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_tambahko, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        pnl_form2.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, -1, -1));

        jPanel30.setBackground(new java.awt.Color(96, 83, 150));

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("Tambah");

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel58, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        pnl_form2.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, -1, -1));

        pnl_kategoriobat.add(pnl_form2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 930, 610));

        jPanel2.add(pnl_kategoriobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 780));

        pnl_satuanobat.setBackground(new java.awt.Color(247, 247, 247));
        pnl_satuanobat.setOpaque(false);
        pnl_satuanobat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_form3.setBackground(new java.awt.Color(247, 247, 247));
        pnl_form3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel31.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pnl_form3.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 80));

        jPanel32.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnl_form3.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(96, 83, 150));
        jLabel13.setText("Satuan Obat");
        pnl_form3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanel33.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pnl_form3.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 530, 20, 80));

        jPanel34.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnl_form3.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 590, 100, 20));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(96, 83, 150));
        jLabel44.setText("Satuan Obat");
        pnl_form3.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        txt_satuanobat.setBackground(new java.awt.Color(247, 247, 247));
        txt_satuanobat.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_satuanobat.setForeground(new java.awt.Color(96, 83, 150));
        txt_satuanobat.setBorder(null);
        pnl_form3.add(txt_satuanobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 690, -1));

        jLabel45.setForeground(new java.awt.Color(96, 83, 150));
        jLabel45.setText(":");
        pnl_form3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 10, -1));

        jSeparator15.setForeground(new java.awt.Color(96, 83, 150));
        jSeparator15.setAlignmentX(1.0F);
        jSeparator15.setAlignmentY(1.0F);
        jSeparator15.setPreferredSize(new java.awt.Dimension(50, 15));
        pnl_form3.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 690, -1));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane3.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tbl_satuanobat.setBackground(new java.awt.Color(247, 247, 247));
        tbl_satuanobat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tbl_satuanobat.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tbl_satuanobat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Satuan"
            }
        ));
        tbl_satuanobat.setGridColor(new java.awt.Color(247, 247, 247));
        tbl_satuanobat.setRowHeight(20);
        tbl_satuanobat.setSelectionBackground(new java.awt.Color(96, 83, 150));
        tbl_satuanobat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_satuanobatMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_satuanobat);

        pnl_form3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 820, 360));

        jPanel35.setBackground(new java.awt.Color(96, 83, 150));

        btn_batalso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_batalso.setForeground(new java.awt.Color(255, 255, 255));
        btn_batalso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_batalso.setText("Batal");
        btn_batalso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_batalso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_batalsoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addComponent(btn_batalso, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addComponent(btn_batalso, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnl_form3.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, -1, 30));

        jPanel36.setBackground(new java.awt.Color(96, 83, 150));

        btn_hapusso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_hapusso.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapusso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_hapusso.setText("Hapus");
        btn_hapusso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_hapusso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapussoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addComponent(btn_hapusso, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel36Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_hapusso, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_form3.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, -1, 30));

        jPanel37.setBackground(new java.awt.Color(96, 83, 150));

        btn_perbaruiso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_perbaruiso.setForeground(new java.awt.Color(255, 255, 255));
        btn_perbaruiso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_perbaruiso.setText("Perbarui");
        btn_perbaruiso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_perbaruiso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_perbaruisoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addComponent(btn_perbaruiso, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addComponent(btn_perbaruiso, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnl_form3.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, -1, 30));

        jPanel38.setBackground(new java.awt.Color(96, 83, 150));

        btn_tambahso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_tambahso.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambahso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_tambahso.setText("Tambah");
        btn_tambahso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tambahso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahsoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_tambahso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_tambahso, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        pnl_form3.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, -1, -1));

        jPanel39.setBackground(new java.awt.Color(96, 83, 150));

        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("Tambah");

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel59, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel59, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        pnl_form3.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, -1, -1));

        pnl_satuanobat.add(pnl_form3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 930, 610));

        jPanel2.add(pnl_satuanobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 780));

        pnl_dataobat.setBackground(new java.awt.Color(247, 247, 247));
        pnl_dataobat.setOpaque(false);
        pnl_dataobat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_form5.setBackground(new java.awt.Color(247, 247, 247));
        pnl_form5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel49.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel49Layout = new javax.swing.GroupLayout(jPanel49);
        jPanel49.setLayout(jPanel49Layout);
        jPanel49Layout.setHorizontalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel49Layout.setVerticalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pnl_form5.add(jPanel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 80));

        jPanel50.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout jPanel50Layout = new javax.swing.GroupLayout(jPanel50);
        jPanel50.setLayout(jPanel50Layout);
        jPanel50Layout.setHorizontalGroup(
            jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel50Layout.setVerticalGroup(
            jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnl_form5.add(jPanel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(96, 83, 150));
        jLabel15.setText("Satuan Obat");
        pnl_form5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanel51.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel51Layout = new javax.swing.GroupLayout(jPanel51);
        jPanel51.setLayout(jPanel51Layout);
        jPanel51Layout.setHorizontalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel51Layout.setVerticalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pnl_form5.add(jPanel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 530, 20, 80));

        jPanel52.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout jPanel52Layout = new javax.swing.GroupLayout(jPanel52);
        jPanel52.setLayout(jPanel52Layout);
        jPanel52Layout.setHorizontalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel52Layout.setVerticalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnl_form5.add(jPanel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 590, 100, 20));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(96, 83, 150));
        jLabel46.setText("Note : Pencarian Berdasarkan No Batch");
        pnl_form5.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        txt_satuanobat1.setBackground(new java.awt.Color(247, 247, 247));
        txt_satuanobat1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_satuanobat1.setForeground(new java.awt.Color(96, 83, 150));
        txt_satuanobat1.setBorder(null);
        pnl_form5.add(txt_satuanobat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 690, -1));

        jLabel47.setForeground(new java.awt.Color(96, 83, 150));
        jLabel47.setText(":");
        pnl_form5.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 10, -1));

        jSeparator16.setForeground(new java.awt.Color(96, 83, 150));
        jSeparator16.setAlignmentX(1.0F);
        jSeparator16.setAlignmentY(1.0F);
        jSeparator16.setPreferredSize(new java.awt.Dimension(50, 15));
        pnl_form5.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 690, -1));

        jScrollPane4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane4.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tbl_satuanobat1.setBackground(new java.awt.Color(247, 247, 247));
        tbl_satuanobat1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tbl_satuanobat1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tbl_satuanobat1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_satuanobat1.setGridColor(new java.awt.Color(247, 247, 247));
        tbl_satuanobat1.setRowHeight(20);
        tbl_satuanobat1.setSelectionBackground(new java.awt.Color(96, 83, 150));
        jScrollPane4.setViewportView(tbl_satuanobat1);

        pnl_form5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 820, 380));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(96, 83, 150));
        jLabel48.setText("No Batch");
        pnl_form5.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        pnl_dataobat.add(pnl_form5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 930, 610));

        jPanel2.add(pnl_dataobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 780));

        pnl_ubahpassword.setBackground(new java.awt.Color(247, 247, 247));
        pnl_ubahpassword.setOpaque(false);
        pnl_ubahpassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_form4.setBackground(new java.awt.Color(247, 247, 247));
        pnl_form4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel40.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pnl_form4.add(jPanel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 80));

        jPanel41.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnl_form4.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(96, 83, 150));
        jLabel14.setText("Ubah Password");
        pnl_form4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanel42.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pnl_form4.add(jPanel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 530, 20, 80));

        jPanel43.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnl_form4.add(jPanel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 590, 100, 20));

        jLabel68.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(96, 83, 150));
        jLabel68.setText("Password Lama");
        pnl_form4.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        txt_passwordlamaup.setBackground(new java.awt.Color(247, 247, 247));
        txt_passwordlamaup.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_passwordlamaup.setForeground(new java.awt.Color(96, 83, 150));
        txt_passwordlamaup.setBorder(null);
        pnl_form4.add(txt_passwordlamaup, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 620, -1));

        jLabel69.setForeground(new java.awt.Color(96, 83, 150));
        jLabel69.setText(":");
        pnl_form4.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 10, -1));

        jSeparator22.setForeground(new java.awt.Color(96, 83, 150));
        jSeparator22.setAlignmentX(1.0F);
        jSeparator22.setAlignmentY(1.0F);
        jSeparator22.setPreferredSize(new java.awt.Dimension(50, 15));
        pnl_form4.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 620, -1));

        jLabel70.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 14)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(96, 83, 150));
        jLabel70.setText("Password Baru");
        pnl_form4.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel71.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 14)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(96, 83, 150));
        jLabel71.setText(":");
        pnl_form4.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 10, -1));

        txt_passwordbaruup.setBackground(new java.awt.Color(247, 247, 247));
        txt_passwordbaruup.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 13)); // NOI18N
        txt_passwordbaruup.setForeground(new java.awt.Color(96, 83, 150));
        txt_passwordbaruup.setBorder(null);
        pnl_form4.add(txt_passwordbaruup, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 620, 19));

        jSeparator23.setForeground(new java.awt.Color(96, 83, 150));
        jSeparator23.setAlignmentX(1.0F);
        jSeparator23.setAlignmentY(1.0F);
        jSeparator23.setPreferredSize(new java.awt.Dimension(50, 15));
        pnl_form4.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 620, -1));

        jPanel44.setBackground(new java.awt.Color(96, 83, 150));

        btn_batalup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_batalup.setForeground(new java.awt.Color(255, 255, 255));
        btn_batalup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_batalup.setText("Batal");

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addComponent(btn_batalup, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addComponent(btn_batalup, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnl_form4.add(jPanel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, -1, 30));

        jPanel45.setBackground(new java.awt.Color(96, 83, 150));

        btn_ubahpasswordup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ubahpasswordup.setForeground(new java.awt.Color(255, 255, 255));
        btn_ubahpasswordup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_ubahpasswordup.setText("Ubah");

        javax.swing.GroupLayout jPanel45Layout = new javax.swing.GroupLayout(jPanel45);
        jPanel45.setLayout(jPanel45Layout);
        jPanel45Layout.setHorizontalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel45Layout.createSequentialGroup()
                .addComponent(btn_ubahpasswordup, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel45Layout.setVerticalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel45Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_ubahpasswordup, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_form4.add(jPanel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, -1, 30));

        jLabel94.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 14)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(96, 83, 150));
        jLabel94.setText("Konfirmasi Password");
        pnl_form4.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel95.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 14)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(96, 83, 150));
        jLabel95.setText(":");
        pnl_form4.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 10, -1));

        txt_konfirmasipasswordup.setBackground(new java.awt.Color(247, 247, 247));
        txt_konfirmasipasswordup.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 13)); // NOI18N
        txt_konfirmasipasswordup.setForeground(new java.awt.Color(96, 83, 150));
        txt_konfirmasipasswordup.setBorder(null);
        pnl_form4.add(txt_konfirmasipasswordup, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 620, 19));

        jSeparator30.setForeground(new java.awt.Color(96, 83, 150));
        jSeparator30.setAlignmentX(1.0F);
        jSeparator30.setAlignmentY(1.0F);
        jSeparator30.setPreferredSize(new java.awt.Dimension(50, 15));
        pnl_form4.add(jSeparator30, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 620, -1));

        pnl_ubahpassword.add(pnl_form4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 930, 610));

        jPanel2.add(pnl_ubahpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 780));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1070, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
        onClick(btn_home);
        onLeaveClick(btn_kategoriobat);
        onLeaveClick(btn_satuanobat);
        onLeaveClick(btn_dataobat);
        onLeaveClick(btn_logout);
        onLeaveClick(btn_ubahpassword);
        
        Indicator1.setOpaque(true);
        Indicator3.setOpaque(false);
        Indicator4.setOpaque(false);
        Indicator6.setOpaque(false);
        Indicator7.setOpaque(false);
        Indicator8.setOpaque(false);
        
        panelHide();
        pnl_home.show();
    }//GEN-LAST:event_btn_homeMouseClicked

    private void btn_kategoriobatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kategoriobatMouseClicked
        onClick(btn_kategoriobat);
        onLeaveClick(btn_home);
        onLeaveClick(btn_satuanobat);
        onLeaveClick(btn_dataobat);
        onLeaveClick(btn_logout);
        onLeaveClick(btn_ubahpassword);
        
        Indicator3.setOpaque(true);
        Indicator1.setOpaque(false);
        Indicator4.setOpaque(false);
        Indicator6.setOpaque(false);
        Indicator7.setOpaque(false);
        Indicator8.setOpaque(false);
        
        panelHide();
        pnl_kategoriobat.show();
        try {
            Kategori.show_kategori(tbl_kategoriobat);
            clearKategori();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_kategoriobatMouseClicked

    private void btn_satuanobatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_satuanobatMouseClicked
        onClick(btn_satuanobat);
        onLeaveClick(btn_kategoriobat);
        onLeaveClick(btn_home);
        onLeaveClick(btn_dataobat);
        onLeaveClick(btn_logout);
        onLeaveClick(btn_ubahpassword);
        
        Indicator4.setOpaque(true);
        Indicator3.setOpaque(false);
        Indicator1.setOpaque(false);
        Indicator6.setOpaque(false);
        Indicator7.setOpaque(false);
        Indicator8.setOpaque(false);
        
        panelHide();
        pnl_satuanobat.show();
        try { 
            clearSatuan();
            Satuan.show_satuan(tbl_satuanobat);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_satuanobatMouseClicked

    private void btn_dataobatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dataobatMouseClicked
        onClick(btn_dataobat);
        onLeaveClick(btn_kategoriobat);
        onLeaveClick(btn_satuanobat);
        onLeaveClick(btn_home);
        onLeaveClick(btn_logout);
        onLeaveClick(btn_ubahpassword);
        
        Indicator6.setOpaque(true);
        Indicator3.setOpaque(false);
        Indicator4.setOpaque(false);
        Indicator1.setOpaque(false);
        Indicator7.setOpaque(false);
        Indicator8.setOpaque(false);
        
        panelHide();
        pnl_dataobat.show();
    }//GEN-LAST:event_btn_dataobatMouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        onClick(btn_logout);
        onLeaveClick(btn_kategoriobat);
        onLeaveClick(btn_satuanobat);
        onLeaveClick(btn_dataobat);
        onLeaveClick(btn_home);
        onLeaveClick(btn_ubahpassword);
        
        Indicator7.setOpaque(true);
        Indicator3.setOpaque(false);
        Indicator4.setOpaque(false);
        Indicator6.setOpaque(false);
        Indicator1.setOpaque(false);
        Indicator8.setOpaque(false);
        
        this.dispose();
        FrmLogin fl = new FrmLogin();
        fl.show();
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);;
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btn_ubahpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ubahpasswordMouseClicked
        onClick(btn_ubahpassword);
        onLeaveClick(btn_kategoriobat);
        onLeaveClick(btn_satuanobat);
        onLeaveClick(btn_dataobat);
        onLeaveClick(btn_home);
        onLeaveClick(btn_logout);
        
        Indicator8.setOpaque(true);
        Indicator3.setOpaque(false);
        Indicator4.setOpaque(false);
        Indicator6.setOpaque(false);
        Indicator1.setOpaque(false);
        Indicator7.setOpaque(false);
        
        panelHide();
        pnl_ubahpassword.show();
    }//GEN-LAST:event_btn_ubahpasswordMouseClicked

    private void btn_tambahkoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahkoMouseClicked
        try {
            Kategori.insert_akun(txt_kategoriobat);
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            Kategori.show_kategori(tbl_kategoriobat);
            clearKategori();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_tambahkoMouseClicked

    private void btn_perbaruikoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_perbaruikoMouseClicked
        try {
            
            Kategori.updateAkun(txt_kategoriobat,id_kategori);
            JOptionPane.showMessageDialog(null, "Data berhasil diperbarui");
            Kategori.show_kategori(tbl_kategoriobat);
            clearKategori();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_perbaruikoMouseClicked

    private void btn_hapuskoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapuskoMouseClicked
        try {
            Kategori.hapusAkun(id_kategori);
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            Kategori.show_kategori(tbl_kategoriobat);
            clearKategori();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_hapuskoMouseClicked

    private void btn_batalkoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalkoMouseClicked
        try {
            clearKategori();
            Kategori.show_kategori(tbl_kategoriobat);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_batalkoMouseClicked

    private void tbl_kategoriobatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_kategoriobatMouseClicked
        try {
            Kategori.getDataTable(tbl_kategoriobat, txt_kategoriobat);
            id_kategori = Kategori.getidKategori(txt_kategoriobat);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tbl_kategoriobatMouseClicked

    private void btn_tambahsoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahsoMouseClicked
        try {
            Satuan.insert_akun(txt_satuanobat);
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            Satuan.show_satuan(tbl_satuanobat);
            clearSatuan();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_tambahsoMouseClicked

    private void btn_perbaruisoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_perbaruisoMouseClicked
        try {
            Satuan.updateAkun(txt_satuanobat, id_satuan);
            JOptionPane.showMessageDialog(null, "Data BErhasil diperbarui");
            Satuan.show_satuan(tbl_satuanobat);
            clearSatuan();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_perbaruisoMouseClicked

    private void btn_hapussoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapussoMouseClicked
        try {
            Satuan.hapusAkun(id_satuan);
            JOptionPane.showMessageDialog(null, "Data Berhasil dihapus");
            Satuan.show_satuan(tbl_satuanobat);
            clearSatuan();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_hapussoMouseClicked

    private void btn_batalsoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalsoMouseClicked
        try {
            clearSatuan();
            Satuan.show_satuan(tbl_satuanobat);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_batalsoMouseClicked

    private void tbl_satuanobatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_satuanobatMouseClicked
        try {
            Satuan.getDataTable(tbl_satuanobat, txt_satuanobat);
            id_satuan = Satuan.getidSatuan(txt_satuanobat);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tbl_satuanobatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardGudang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Indicator1;
    private javax.swing.JPanel Indicator3;
    private javax.swing.JPanel Indicator4;
    private javax.swing.JPanel Indicator6;
    private javax.swing.JPanel Indicator7;
    private javax.swing.JPanel Indicator8;
    private javax.swing.JLabel btn_batalko;
    private javax.swing.JLabel btn_batalso;
    private javax.swing.JLabel btn_batalup;
    private javax.swing.JPanel btn_dataobat;
    private javax.swing.JLabel btn_hapusko;
    private javax.swing.JLabel btn_hapusso;
    private javax.swing.JPanel btn_home;
    private javax.swing.JPanel btn_kategoriobat;
    private javax.swing.JPanel btn_logout;
    private javax.swing.JLabel btn_perbaruiko;
    private javax.swing.JLabel btn_perbaruiso;
    private javax.swing.JPanel btn_satuanobat;
    private javax.swing.JLabel btn_tambahko;
    private javax.swing.JLabel btn_tambahso;
    private javax.swing.JPanel btn_ubahpassword;
    private javax.swing.JLabel btn_ubahpasswordup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JLabel lbl_namalengkap;
    private javax.swing.JPanel pnl_dataobat;
    private javax.swing.JPanel pnl_form2;
    private javax.swing.JPanel pnl_form3;
    private javax.swing.JPanel pnl_form4;
    private javax.swing.JPanel pnl_form5;
    private javax.swing.JPanel pnl_form6;
    private javax.swing.JPanel pnl_home;
    private javax.swing.JPanel pnl_kategoriobat;
    private javax.swing.JPanel pnl_satuanobat;
    private javax.swing.JPanel pnl_ubahpassword;
    private javax.swing.JTable tbl_kategoriobat;
    private javax.swing.JTable tbl_satuanobat;
    private javax.swing.JTable tbl_satuanobat1;
    private javax.swing.JTextField txt_kategoriobat;
    private javax.swing.JTextField txt_konfirmasipasswordup;
    private javax.swing.JTextField txt_passwordbaruup;
    private javax.swing.JTextField txt_passwordlamaup;
    private javax.swing.JTextField txt_satuanobat;
    private javax.swing.JTextField txt_satuanobat1;
    // End of variables declaration//GEN-END:variables
}
